spring.application.name=wallet

spring.datasource.url=jdbc:postgresql://localhost:5432/wallet
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
logging.level.org.springframework.security=DEBUG
spring.jpa.show-sql=true
logging.level.org.springframework.jdbc.datasource.init.ScriptUtils=DEBUG

###########################################################################################
#                                   liquibase                                             #
###########################################################################################

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.url=jdbc:postgresql://localhost:5432/wallet
spring.liquibase.user=postgres
spring.liquibase.password=postgres
spring.liquibase.enabled=true
